pipeline:
  # restore-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   restore: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.yarn-cache
  #     - ./node_modules

  install:
    image: node:8.12.0-alpine
    environment:
      - NODE_ENV=production
    commands:
      - yarn config set cache-folder .yarn-cache
      - yarn install --prod

  bake:
    image: node:8.12.0-alpine
    environment:
      - HOST=access-denied.apps.fivetwentyseven.com
      - PORT=443
    commands:
      - yarn bake

  push-data:
    image: node:8.12.0-alpine
    secrets: [aws_access_key_id, aws_secret_access_key]
    commands:
      - yarn push-data
    when:
      branch: preview

  generate:
    image: node:8.12.0-alpine
    environment:
      - HOST=apps.publicintegrity.org
      - PORT=443
      - NODE_ENV=production
    commands:
      - yarn generate

  push:
    image: node:8.12.0-alpine
    secrets: [aws_access_key_id, aws_secret_access_key]
    commands:
      - yarn push
    when:
      branch: preview

  # rebuild-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   rebuild: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.yarn-cache
  #     - ./node_modules
  #   when:
  #     branch: master

  # flush-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   flush: true

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    template: >
      {{#success build.status}}
        published https://apps.publicintegrity.org/abandoned-in-america/
      {{else}}
        failed publishing https://apps.publicintegrity.org/abandoned-in-america/
      {{/success}}
    when:
      branch: preview
